"""db path check

Revision ID: c5c9b2855c3a
Revises: 
Create Date: 2026-02-03 06:15:58.783165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c9b2855c3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # SQLite safety: if bootstrap tables already exist (e.g., from create_all),
    # skip this bulk create to avoid "table already exists" failures.
    try:
        bind = op.get_bind()
        existing = set(sa.inspect(bind).get_table_names())
        if "audit_logs" in existing:
            return
    except Exception:
        pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autopilot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commission_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_rules_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_rules_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_rules_state'), ['state'], unique=False)

    op.create_table('disabled_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disabled_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disabled_listings_listing_id'), ['listing_id'], unique=True)

    op.create_table('disabled_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disabled_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disabled_users_user_id'), ['user_id'], unique=True)

    op.create_table('driver_job_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('pickup', sa.String(length=255), nullable=False),
    sa.Column('dropoff', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_jobs_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_jobs_order_id'), ['order_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('merchant_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_user_id', sa.Integer(), nullable=False),
    sa.Column('rater_name', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('to', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('payout_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('recipient_code', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shortlets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('locality', sa.String(length=96), nullable=True),
    sa.Column('lga', sa.String(length=96), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('nightly_price', sa.Float(), nullable=False),
    sa.Column('cleaning_fee', sa.Float(), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('baths', sa.Integer(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('available_to', sa.Date(), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('property_type', sa.String(length=64), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('house_rules', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('verification_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('gross_amount', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('commission_total', sa.Float(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('kyc_tier', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawals_user_id'), ['user_id'], unique=False)

    op.create_table('bond_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspector_user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference_type', sa.String(length=24), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bond_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bond_events_inspector_user_id'), ['inspector_user_id'], unique=False)

    op.create_table('driver_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('plate_number', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('locality', sa.String(length=96), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('inspector_bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspector_user_id', sa.Integer(), nullable=False),
    sa.Column('bond_currency', sa.String(length=8), nullable=False),
    sa.Column('bond_required_amount', sa.Float(), nullable=False),
    sa.Column('bond_available_amount', sa.Float(), nullable=False),
    sa.Column('bond_reserved_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_topup_at', sa.DateTime(), nullable=True),
    sa.Column('last_slash_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspector_bonds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspector_bonds_inspector_user_id'), ['inspector_user_id'], unique=True)

    op.create_table('inspector_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('completed_inspections', sa.Integer(), nullable=False),
    sa.Column('failed_inspections', sa.Integer(), nullable=False),
    sa.Column('fraud_flags', sa.Integer(), nullable=False),
    sa.Column('dispute_overturned_count', sa.Integer(), nullable=False),
    sa.Column('dispute_audit_count', sa.Integer(), nullable=False),
    sa.Column('avg_turnaround_minutes', sa.Float(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('reputation_tier', sa.String(length=16), nullable=False),
    sa.Column('last_score_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspector_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspector_profiles_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspector_profiles_reputation_score'), ['reputation_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspector_profiles_reputation_tier'), ['reputation_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspector_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('kyc_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=140), nullable=True),
    sa.Column('id_type', sa.String(length=64), nullable=True),
    sa.Column('id_number', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('locality', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_user_id'), ['user_id'], unique=False)

    op.create_table('merchant_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=160), nullable=True),
    sa.Column('shop_category', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('locality', sa.String(length=96), nullable=True),
    sa.Column('lga', sa.String(length=96), nullable=True),
    sa.Column('total_sales', sa.Float(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('successful_deliveries', sa.Integer(), nullable=False),
    sa.Column('cancelled_orders', sa.Integer(), nullable=False),
    sa.Column('disputes', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('bank_name', sa.String(length=80), nullable=True),
    sa.Column('account_number', sa.String(length=32), nullable=True),
    sa.Column('account_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_requests_user_id'), ['user_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shortlet_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortlet_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=120), nullable=True),
    sa.Column('guest_phone', sa.String(length=64), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shortlet_id'], ['shortlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=140), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notif_in_app', sa.Boolean(), nullable=False),
    sa.Column('notif_sms', sa.Boolean(), nullable=False),
    sa.Column('notif_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('reserved_balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=True)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('delivery_fee', sa.Float(), nullable=False),
    sa.Column('pickup', sa.String(length=200), nullable=True),
    sa.Column('dropoff', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_reference', sa.String(length=80), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('escrow_status', sa.String(length=16), nullable=False),
    sa.Column('escrow_hold_amount', sa.Float(), nullable=False),
    sa.Column('escrow_currency', sa.String(length=8), nullable=False),
    sa.Column('escrow_held_at', sa.DateTime(), nullable=True),
    sa.Column('escrow_release_at', sa.DateTime(), nullable=True),
    sa.Column('escrow_refund_at', sa.DateTime(), nullable=True),
    sa.Column('escrow_disputed_at', sa.DateTime(), nullable=True),
    sa.Column('release_condition', sa.String(length=24), nullable=False),
    sa.Column('release_timeout_hours', sa.Integer(), nullable=False),
    sa.Column('inspection_required', sa.Boolean(), nullable=False),
    sa.Column('inspection_status', sa.String(length=24), nullable=False),
    sa.Column('inspection_outcome', sa.String(length=16), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('inspection_requested_at', sa.DateTime(), nullable=True),
    sa.Column('inspection_on_my_way_at', sa.DateTime(), nullable=True),
    sa.Column('inspection_arrived_at', sa.DateTime(), nullable=True),
    sa.Column('inspection_inspected_at', sa.DateTime(), nullable=True),
    sa.Column('inspection_closed_at', sa.DateTime(), nullable=True),
    sa.Column('inspection_evidence_urls', sa.Text(), nullable=True),
    sa.Column('inspection_note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_escrow_status'), ['escrow_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_inspection_outcome'), ['inspection_outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_inspection_status'), ['inspection_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_inspector_id'), ['inspector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_payment_reference'), ['payment_reference'], unique=False)

    op.create_table('wallet_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_txns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_txns_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_txns_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_txns_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('inspection_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('inspector_user_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_audits_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_audits_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_audits_inspector_user_id'), ['inspector_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_audits_order_id'), ['order_id'], unique=False)

    op.create_table('inspection_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('inspector_user_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('comment', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_reviews_inspector_user_id'), ['inspector_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_reviews_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_reviews_reviewer_user_id'), ['reviewer_user_id'], unique=False)

    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_events_actor_user_id'))

    op.drop_table('order_events')
    with op.batch_alter_table('inspection_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_reviews_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_reviews_order_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_reviews_inspector_user_id'))

    op.drop_table('inspection_reviews')
    with op.batch_alter_table('inspection_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_audits_order_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_audits_inspector_user_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_audits_decision'))
        batch_op.drop_index(batch_op.f('ix_inspection_audits_admin_user_id'))

    op.drop_table('inspection_audits')
    with op.batch_alter_table('wallet_txns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_txns_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_txns_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_txns_reference'))

    op.drop_table('wallet_txns')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_payment_reference'))
        batch_op.drop_index(batch_op.f('ix_orders_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_orders_listing_id'))
        batch_op.drop_index(batch_op.f('ix_orders_inspector_id'))
        batch_op.drop_index(batch_op.f('ix_orders_inspection_status'))
        batch_op.drop_index(batch_op.f('ix_orders_inspection_outcome'))
        batch_op.drop_index(batch_op.f('ix_orders_escrow_status'))
        batch_op.drop_index(batch_op.f('ix_orders_driver_id'))
        batch_op.drop_index(batch_op.f('ix_orders_buyer_id'))

    op.drop_table('orders')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))

    op.drop_table('wallets')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))

    op.drop_table('user_settings')
    op.drop_table('support_tickets')
    op.drop_table('shortlet_bookings')
    op.drop_table('receipts')
    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_requests_user_id'))

    op.drop_table('payout_requests')
    op.drop_table('notifications')
    op.drop_table('merchant_profiles')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_user_id'))
        batch_op.drop_index(batch_op.f('ix_listings_owner_id'))

    op.drop_table('listings')
    op.drop_table('kyc_requests')
    with op.batch_alter_table('inspector_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspector_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_inspector_profiles_reputation_tier'))
        batch_op.drop_index(batch_op.f('ix_inspector_profiles_reputation_score'))
        batch_op.drop_index(batch_op.f('ix_inspector_profiles_region'))

    op.drop_table('inspector_profiles')
    with op.batch_alter_table('inspector_bonds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspector_bonds_inspector_user_id'))

    op.drop_table('inspector_bonds')
    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_profiles_user_id'))

    op.drop_table('driver_profiles')
    with op.batch_alter_table('bond_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bond_events_inspector_user_id'))

    op.drop_table('bond_events')
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawals_user_id'))

    op.drop_table('withdrawals')
    op.drop_table('webhook_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('shortlets')
    op.drop_table('payouts')
    op.drop_table('payout_recipients')
    op.drop_table('payment_transactions')
    op.drop_table('payment_intents')
    op.drop_table('notification_queue')
    op.drop_table('merchant_reviews')
    op.drop_table('idempotency_keys')
    with op.batch_alter_table('driver_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_jobs_order_id'))
        batch_op.drop_index(batch_op.f('ix_driver_jobs_driver_id'))

    op.drop_table('driver_jobs')
    op.drop_table('driver_job_offers')
    with op.batch_alter_table('disabled_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disabled_users_user_id'))

    op.drop_table('disabled_users')
    with op.batch_alter_table('disabled_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disabled_listings_listing_id'))

    op.drop_table('disabled_listings')
    with op.batch_alter_table('commission_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_rules_state'))
        batch_op.drop_index(batch_op.f('ix_commission_rules_kind'))
        batch_op.drop_index(batch_op.f('ix_commission_rules_category'))

    op.drop_table('commission_rules')
    op.drop_table('autopilot_settings')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
